### PR TITLE
feat: adds comment to transformed files

### PR DESCRIPTION
**Pull request by madou**
Outstanding question: How can we mock `package.json` globally so we don't have to keep updating tests when new versions are released? Tried using `moduleNameMapper` to no avail.

### CODE REVIEW

**Comment by pgmanutd** [comment]
> Outstanding question: How can we mock `package.json` globally so we don't have to keep updating tests when new versions are released? Tried using `moduleNameMapper` to no avail.

Let me see if anything we can do something about this. This will break tests everytime we release new version.

**Comment by pgmanutd** [comment]
Only way (kind of hacky) I figured out is doing something like this:

```ts
const compiledBabelVersion = process.env.COMPILED_BABEL_VERSION || pkgJson.version;
```

and setting `process.env.COMPILED_BABEL_VERSION` in jest setup file.

**Comment by madou** [comment]
> Only way (kind of hacky) I figured out is doing something like this:
> 
> ```ts
> const compiledBabelVersion = process.env.COMPILED_BABEL_VERSION || pkgJson.version;
> ```
> 
> and setting `process.env.COMPILED_BABEL_VERSION` in jest setup file.

it's shit but i'll do it, haha!

**Review by pgmanutd — APPROVED** [review]
lgtm

**Pull request merged**
