### PR TITLE
chore: renames core pkg to react

### PR DESCRIPTION
**Pull request by madou**
- renames `@compiled/core` to `@compiled/react`
- removes + moves `@compiled/runtime` to `@compiled/react/runtime`
- removes CC CS and ax from primary entrypoint and expose them from `react/runtime` entrypoint only

### CODE REVIEW

**Comment by pgmanutd** [comment]
Big PR 😄. Damn this will break my CLI PR again. Hehe. Anyways I can see more tasks in addition to following ones in this PR 🤔:

- renames @compiled/core to @compiled/react
- removes + moves @compiled/runtime to @compiled/react/runtime

**Comment by madou** [comment]
> Big PR 😄. Damn this will break my CLI PR again. Hehe. Anyways I can see more tasks in addition to following ones in this PR 🤔:
> 
>     * renames @compiled/core to @compiled/react
> 
>     * removes + moves @compiled/runtime to @compiled/react/runtime

what else?

**Comment by pgmanutd** [comment]
> > Big PR 😄. Damn this will break my CLI PR again. Hehe. Anyways I can see more tasks in addition to following ones in this PR 🤔:
> > ```
> > * renames @compiled/core to @compiled/react
> > 
> > * removes + moves @compiled/runtime to @compiled/react/runtime
> > ```
> 
> what else? remove from entrypoint change? ill add to description

No worries. All good 😃. Let me check once. I fell ill yesterday. Didn't get much time to look over the things 😞

**Comment by madou** [comment]
take it easy

**Comment by pgmanutd** [comment]
> take it easy

Thanks ❤️. Long weekend ruined because of cold.

**Review by pgmanutd — APPROVED** [review]
lgtm

**Pull request merged**
