### PR TITLE
using globalThis to detect if running in node

### PR DESCRIPTION
**Pull request by alexreardon**
From here: https://github.com/atlassian-labs/compiled/pull/314/files#r503583214

This will require consumers be running on node `> 12.x`

### CODE REVIEW

**Comment by madou** [comment]
can we do anything to ensure consumers are on node 12? throw during run?

**Comment by alexreardon** [comment]
It looks like your minimum node version is not defined for the project
You will want to do something like this:

```json
{ 
  "engines" : { 
    "node" : ">=12.0.0" 
   },
  "engineStrict" : true,
}
```
https://stackoverflow.com/questions/29349684/how-can-i-specify-the-required-node-js-version-in-package-json

You are using `nvm` but that only supports local running of the repo

**Comment by alexreardon** [comment]
I can add a PR for that too if you want 😊

**Comment by madou** [comment]
yes please

what happens if someone in the browser wants to be clever and sets:

```js
global = globalThis
```

🤔

**Comment by alexreardon** [comment]
I've added another check. 

But i've found that `globalThis` is writable. So you could do this:

```
globalThis = whatever
```

So there is some level of risk in using globalThis.

That said, I would think that sort of behaviour is unlikely

**Comment by alexreardon** [comment]
I think this way of detecting node is a bit more future proof (i'm not sure if the current toString approach is public API). 

That said, it would be fine to keep the current approach

**Comment by madou** [comment]
hey looks like a test is failing

**Comment by alexreardon** [comment]
I can dive in and fix if you are happy to proceed with this approach to `node` sniffing

**Comment by alexreardon** [comment]
I ran into a bit of a wall here because `global` can be created on the client and `globalThis` can be re-assigned

**Review by madou — APPROVED** [review]
lgtm

@pgmanutd how about you? this relates to this https://nodejs.org/api/process.html#process_process_release

**Comment by pgmanutd** [comment]
> lgtm
> 
> @pgmanutd how about you? this relates to this https://nodejs.org/api/process.html#process_process_release

@madou: What about 🤔
```ts
window.process = {release: {name: 'node'}};
// or
global.process = {release: {name: 'not node'}};
```

**Comment by madou** [comment]
@pgmanutd interestingly this code should never be executed in the browser anyway because it of the `browser` entrypoint 😄 

so I think it's reasonable safe TBH

**Comment by pgmanutd** [comment]
> @pgmanutd interestingly this code should never be executed in the browser anyway because it of the `browser` entrypoint 😄
> 
> so I think it's reasonable safe TBH

🤔 but `global.process = {release: {name: 'not node'}};` can be executed in node environment 🤔 
Anyways this works. Was just worried about this case ^^

**Comment by alexreardon** [comment]
I'm not too worried about people overriding `process`. I'm more worried about that `toString()` behaviour changing

**Review by madou — APPROVED** [review]
lgtm

**Comment by pgmanutd** [comment]
> I'm not too worried about people overriding `process`. I'm more worried about that `toString()` behaviour changing

❤️ nice. Works for me. 😉

**Review by pgmanutd — APPROVED** [review]

**Pull request merged**
